# Generated by Django 4.0.1 on 2022-01-25 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 20, 2, 46, 978759, tzinfo=utc)),
        ),
    ]
